### PR TITLE
75 improve importer script

### LINKED ISSUE #75: Improve importer script
Allow passing in a resource ID : change post request to put so you can create resource with ID passed in

### PR DESCRIPTION
**Pull request by TraciebelWairimu**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #75

The following use cases are what is implemented:

If the 'method' is == create:
- and new id is provided -> use the new id to create new resource
- and no id is provided -> generate a new id and use that to create new resource

If the 'method' is == update:
- and id existing in server is provided -> update resource with provided id
- and a new id is provided -> use the new id to create new resource
- and no id is provided -> generate a new id and use that to create new resource

Is there any case that is missing above? or anything that needs correction?
If we all agree with the above we can potentially eliminate the "method" column as well 

**Engineer Checklist**
- [ ] I have run `./gradlew spotlessApply` to check my code follows the project's style guide
- [ ] I have built and run the efsity jar to verify my change fixes the issue and/or does not break the application

### CODE REVIEW

**Review by Wambere — APPROVED** [review]

**Comment by Wambere** [comment]
The following use cases are what is implemented:

If the 'method' is == create:
- and new id is provided -> use the new id to create new resource
- and no id is provided -> generate a new id and use that to create new resource

If the 'method' is == update:
- and id existing in server is provided -> update resource with provided id
- and a new id is provided -> use the new id to create new resource
- and no id is provided -> generate a new id and use that to create new resource

Is there any case that is missing above? or anything that needs correction?
If we all agree with the above we can potentially eliminate the "method" column as well

**Comment by dubdabasoduba** [comment]
> If the 'method' is == update:
> 
> - and id existing in server is provided -> update resource with provided id
> - and a new id is provided -> use the new id to create new resource
> - and no id is provided -> generate a new id and use that to create new resource

@Wambere  for the `update` could we throw errors instead?  

From a usage perspective, if the user of the tool does an `update` they expect to update whatever exists. if we go ahead and create new resources we are going to have duplicated data which might lead to issues will analytics if the newly created resources are used for assignments.

**Comment by dubdabasoduba** [comment]
> If the 'method' is == create:
> 
> - and new ID is provided -> use the new id to create a new resource
> - and no ID is provided -> generate a new ID and use that to create a new resource

@Wambere is there a way we can save the newly created IDs somewhere so the users can reference them on their CSVs?

**Comment by Wambere** [comment]
@dubdabasoduba thanks for the feedback, created 2 new issues for the above

**Pull request merged**
